[package]
name = "leo-status"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
hidapi = "2.4.1"
humantime = "2.1.0"
serde = { version = "1.0.193", features = ["serde_derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"
