[package]
name = "leo-status"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

leo-status-driver = { path = "../leo-status-driver" }
serde = { version = "1.0.195", features = ["serde_derive"] }
serde_json = "1.0.111"
hidapi = "2.5.0"
clap = { version = "4.4.16", features = ["derive"] }
humantime = "2.1.0"
tiny_http = "0.12"
