name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust - ${{ matrix.toolchain }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: apt-get install libhidapi-dev
    - name: Set rust version
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
