name: Rust

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust - ${{ matrix.build }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            install_deps_script: |
              sudo apt-get install libhidapi-dev libudev-dev

          - build: macos
            os: macos-latest

          - build: windows
            os: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: ${{ matrix.install_deps_script }}
      if: matrix.install_deps_script != ''
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.build }}
        path: target/release/leo-status*

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/download-artifact@v4
      with:
        path: ${{ github.workspace }}/artifacts

    - run: |
        mkdir ${{ github.workspace }}/bundle
        
        cd ${{ github.workspace }}/artifacts
        find . -maxdepth 1 -mindepth 1 -type d -exec tar cvf  ${{ github.workspace }}/bundle/{}.tar {}  \;

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: |
          ${{ github.workspace }}/bundle/*.tar

    permissions:
      contents: write
