name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust - ${{ matrix.os }} - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            install_deps_script: |
              sudo apt-get install libhidapi-dev libudev-dev

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: ${{ matrix.install_deps_script }}
      if: matrix.install_deps_script != ''
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.build }}
        path: target/release/leo-status*
